/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tangzy_jnilibrary_jni_JNITest */

#ifndef _Included_com_tangzy_jnilibrary_jni_JNITest
#define _Included_com_tangzy_jnilibrary_jni_JNITest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tangzy_jnilibrary_jni_JNITest
 * Method:    getJNIName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tangzy_jnilibrary_jni_JNITest_getJNIName
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
